use imece;
create table ALTERNATIVE_BRAND(
BRAND_BARCODE INTEGER,
M_SYSCODE INTEGER,
ALTERNATIVE_BRAND_BARCODE INTEGER,
ALTERNATIVE_M_SYSCODE INTEGER,
primary key (BRAND_BARCODE, M_SYSCODE, ALTERNATIVE_BRAND_BARCODE, ALTERNATIVE_M_SYSCODE)
);