use imece;
create table FLOW(
Source_LOT_ID INTEGER,
Source_ORG_ID INTEGER,
TARGET_LOT_ID INTEGER,
TARGET_ORG_ID INTEGER,
BRAND_BARCODE varchar(50),
ALTERNATIVE_M_SYSCODE VARCHAR(10),
primary key (Source_LOT_ID, Source_ORG_ID, TARGET_LOT_ID, TARGET_ORG_ID, BRAND_BARCODE, ALTERNATIVE_M_SYSCODE)
);