USE imece;
CREATE TABLE PRODUCT_FEATURES(
M_SYSCODE  int not null auto_increment,
FEATURE_ID INT,
MINVAL FLOAT,
MAXVAL FLOAT,
PRIMARY KEY (MINVAL,MAXVAL) ,
FOREIGN KEY(M_SYSCODE) REFERENCES PRODUCT(m_syscode),
FOREIGN KEY(FEATURE_ID) REFERENCES FEATURES (FEATURE_ID)
);